name: "granite_embed"
backend: "python"
max_batch_size: 32

input [
  {
    name: "texts"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "vectors"
    data_type: TYPE_FP32
    dims: [ -1, 768 ]
  },
  {
    name: "meta"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [{ kind: KIND_GPU, count: 1 }]

parameters {
  key: "EXECUTION_ENV_PATH"
  value: { string_value: "/workspace/riprap_env.tar.gz" }
}
